remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Semyon Osadchii - HAN MADS Portfolio
description: Machine learning portfolio for the HAN Master of Applied Data Science
